title: STAGS
description: Strategic Technical Analysis for Golf Stats
theme: just-the-docs

url: https://neilsummers.github.io/stags

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
